package com.turant.subscriber;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Real assertions for SubscriberCellStatsService — covers primary (dump/agg), fallback (stats), and true-zero.
 * This is the file RELEASE_NOTES falsely claimed existed; now it actually does.
 */
@SpringBootTest
@ActiveProfiles("test")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
class SubscriberMatcherTest {

    @Autowired
    private JdbcTemplate jdbc;

    private SubscriberCellStatsService svc;

    @BeforeEach
    void setUp() {
        try { jdbc.execute("DROP TABLE IF EXISTS turant_agg.cell_subscriber_agg"); } catch(Exception ignore){}
        try { jdbc.execute("DROP SCHEMA IF EXISTS turant_agg CASCADE"); } catch(Exception ignore){}
        jdbc.execute("CREATE SCHEMA IF NOT EXISTS turant_agg");
        jdbc.execute("CREATE TABLE turant_agg.cell_subscriber_agg (serving_cell_id VARCHAR(255) PRIMARY KEY, sub_count BIGINT, distinct_count BIGINT)");
        jdbc.execute("DROP TABLE IF EXISTS cell_subscriber_stats");
        jdbc.execute("CREATE TABLE cell_subscriber_stats (cell_id VARCHAR(255) PRIMARY KEY, subscriber_count BIGINT, unique_subscriber_count BIGINT)");
        try { jdbc.execute("DROP TABLE IF EXISTS subscriber_dump"); } catch(Exception ignore){}
        jdbc.execute("CREATE TABLE subscriber_dump (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, serving_cell_id VARCHAR(255), msisdn VARCHAR(255), imsi VARCHAR(255), technology VARCHAR(32))");

        svc = new SubscriberCellStatsService(
                jdbc, "enabled",
                "cell_subscriber_stats", "cell_id", "subscriber_count", "unique_subscriber_count",
                "subscriber_dump", "serving_cell_id", "msisdn",
                "turant_agg.cell_subscriber_agg", "serving_cell_id", "sub_count", "distinct_count",
                4);
    }

    @Test
    @Order(1)
    void primaryPathDumpOrAggHasDataReturnsCorrectCounts() {
        jdbc.update("INSERT INTO turant_agg.cell_subscriber_agg (serving_cell_id, sub_count, distinct_count) VALUES (?,?,?)", "CELL-1", 10, 9);
        jdbc.update("INSERT INTO turant_agg.cell_subscriber_agg (serving_cell_id, sub_count, distinct_count) VALUES (?,?,?)", "CELL-2", 20, 18);
        jdbc.update("INSERT INTO turant_agg.cell_subscriber_agg (serving_cell_id, sub_count, distinct_count) VALUES (?,?,?)", "CELL-3", 0, 0);
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)", "CELL-1", "919000000001", "IMSI01", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)", "CELL-1", "919000000002", "IMSI02", "5G");

        List<String> target = List.of("CELL-1","CELL-2","CELL-3","CELL-UNKNOWN");

        long[] res = svc.countAndDistinctByCellIds(target);
        assertEquals(30, res[0], "total must be 30 from agg primary");
        assertEquals(27, res[1], "distinct must be 27");
        assertEquals(2, svc.countByCellIds(target), "countByCellIds primary is dump (2 rows) not agg");
        assertEquals(2, svc.uniqueCountByCellIds(target), "uniqueCountByCellIds primary is dump distinct 2");
    }

    @Test
    @Order(2)
    void fallbackPathDumpEmptyStatsHasDataReturnsStatsSum() {
        jdbc.execute("DELETE FROM turant_agg.cell_subscriber_agg");
        jdbc.execute("DELETE FROM subscriber_dump");
        jdbc.update("INSERT INTO cell_subscriber_stats (cell_id, subscriber_count, unique_subscriber_count) VALUES (?,?,?)", "CELL-FB-1", 100, 95);
        jdbc.update("INSERT INTO cell_subscriber_stats (cell_id, subscriber_count, unique_subscriber_count) VALUES (?,?,?)", "CELL-FB-2", 200, 180);

        List<String> target = List.of("CELL-FB-1","CELL-FB-2");

        assertEquals(300, svc.countByCellIds(target));
        assertEquals(275, svc.uniqueCountByCellIds(target));
        long[] res = svc.countAndDistinctByCellIds(target);
        assertEquals(300, res[0]);
        assertEquals(275, res[1]);
    }

    @Test
    @Order(3)
    void trueZeroCaseNeitherHasDataReturnsZero() {
        jdbc.execute("DELETE FROM turant_agg.cell_subscriber_agg");
        jdbc.execute("DELETE FROM subscriber_dump");
        jdbc.execute("DELETE FROM cell_subscriber_stats");

        List<String> target = List.of("CELL-ZERO-1","CELL-ZERO-2");
        long[] res = svc.countAndDistinctByCellIds(target);
        assertEquals(0, res[0]);
        assertEquals(0, res[1]);
        assertEquals(0, svc.countByCellIds(target));
        assertEquals(0, svc.uniqueCountByCellIds(target));
        long streamed = svc.forEachMsisdn(target, msisdn -> fail("should not be called"));
        assertEquals(0, streamed);
    }

    @Test
    @Order(4)
    void forEachMsisdnStreamsDistinctCorrectly() {
        jdbc.execute("DELETE FROM turant_agg.cell_subscriber_agg");
        jdbc.execute("DELETE FROM cell_subscriber_stats");
        jdbc.execute("DELETE FROM subscriber_dump");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)", "CELL-X", "919000000001", "IMSI01", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)", "CELL-X", "919000000002", "IMSI02", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)", "CELL-X", "919000000003", "IMSI03", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)", "CELL-Y", "919000000002", "IMSI02", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)", "CELL-Y", "919000000004", "IMSI04", "5G");

        List<String> target = List.of("CELL-X","CELL-Y");
        Set<String> distinctCollected = ConcurrentHashMap.newKeySet();
        long streamedCount = svc.forEachMsisdn(target, distinctCollected::add);
        assertEquals(4, streamedCount, "forEachMsisdn SELECT DISTINCT should return 4 distinct");
        assertEquals(4, distinctCollected.size());
        assertTrue(distinctCollected.contains("919000000001"));
        assertTrue(distinctCollected.contains("919000000004"));

        long[] res = svc.countAndDistinctByCellIds(target);
        assertEquals(5, res[0], "total rows 5 (X 3 + Y 2)");
        assertEquals(4, res[1], "distinct 4 (002 duplicate)");
    }

    @Test
    @Order(5)
    void countByCellIdsHandlesEmptyAndNullInput() {
        assertEquals(0, svc.countByCellIds(List.of()));
        assertEquals(0, svc.countByCellIds(null));
        assertEquals(0, svc.uniqueCountByCellIds(List.of()));
        assertEquals(0, svc.forEachMsisdn(List.of(), s -> fail()));
        assertArrayEquals(new long[]{0,0}, svc.countAndDistinctByCellIds(List.of()));
    }
}
