package com.turant.ews;

import com.turant.cellsite.TowerSource;
import com.turant.simulation.TestDataFixtures;
import com.turant.types.cap.CapAlert;
import com.turant.types.tower.CellTower;
import org.junit.jupiter.api.*;
import org.mockserver.integration.ClientAndServer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import java.util.List;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

/**
 * Proves Activity 7 is actually executed from AlertPipeline and that the EWS report
 * contains real pipeline values (towerCount, expectedRecipients, etc.) and is received
 * by the controlled local EWS endpoint via HTTP (or in-memory fallback with store).
 */
@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "turant.ews.mode=local",
        "turant.ews.local-url=",
        "turant.ews.connect-timeout=2s",
        "turant.ews.read-timeout=2s",
        "springdoc.api-docs.enabled=false",
        "springdoc.swagger-ui.enabled=false"
})
class EwsPipelineIntegrationTest {

    @Autowired
    private com.turant.pipeline.AlertPipeline alertPipeline;

    @Autowired
    private JdbcTemplate jdbc;

    @Autowired
    private LocalEwsStore localStore;

    @Autowired
    private com.turant.ews.config.EwsProperties props;

    private static ClientAndServer ewsMockServer;

    @BeforeAll
    static void startEwsMock() {
        ewsMockServer = ClientAndServer.startClientAndServer(18084);
    }

    @AfterAll
    static void stopEwsMock() {
        if (ewsMockServer != null) ewsMockServer.stop();
    }

    @BeforeEach
    void setup() {
        if (ewsMockServer != null) ewsMockServer.reset();
        localStore.clear();
        props.setMode("local");
        props.setLocalUrl("");
        // Setup deterministic subscriber set (same as PipelineSmppIntegrationTest)
        jdbc.execute("CREATE TABLE IF NOT EXISTS sim_cell_towers (site_id VARCHAR(255) PRIMARY KEY, cell_id VARCHAR(255) UNIQUE, latitude DOUBLE, longitude DOUBLE, coverage_radius_m DOUBLE)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS subscriber_dump (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, msisdn VARCHAR(255), serving_cell_id VARCHAR(255), imsi VARCHAR(255))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS cell_subscriber_stats (cell_id VARCHAR(255) PRIMARY KEY, subscriber_count BIGINT, unique_subscriber_count BIGINT)");
        jdbc.update("DELETE FROM subscriber_dump");
        jdbc.update("DELETE FROM sim_cell_towers");
        jdbc.update("DELETE FROM cell_subscriber_stats");
        for (int i = 1; i <= 3; i++) {
            String siteId = "ews-site-" + i;
            String cellId = "EWS-CELL-00" + i;
            jdbc.update("INSERT INTO sim_cell_towers (site_id, cell_id, latitude, longitude, coverage_radius_m) VALUES (?,?,?,?,?)", siteId, cellId, 28.61 + i * 0.001, 77.20 + i * 0.001, 500.0);
            jdbc.update("INSERT INTO subscriber_dump (msisdn, serving_cell_id, imsi) VALUES (?,?,?)", "9190000000" + (20 + i), cellId, "40445123456780" + i);
            jdbc.update("INSERT INTO cell_subscriber_stats (cell_id, subscriber_count, unique_subscriber_count) VALUES (?,?,?)", cellId, 1, 1);
        }
    }

    @Test
    void pipelineInvokesEwsWithRealValues() throws Exception {
        assertEquals("local", props.getMode());
        TowerSource src = new TowerSource() {
            @Override public String getName() { return "ews-test"; }
            @Override public java.util.concurrent.CompletableFuture<com.turant.cellsite.TowerResolutionResult> findTowersInZone(com.turant.types.tower.GeoZone z, FindTowersOptions o) {
                List<CellTower> towers = List.of(
                        new CellTower("ews-site-1", "EWS-CELL-001", 28.611, 77.201, 500.0, null),
                        new CellTower("ews-site-2", "EWS-CELL-002", 28.612, 77.202, 500.0, null),
                        new CellTower("ews-site-3", "EWS-CELL-003", 28.613, 77.203, 500.0, null)
                );
                return java.util.concurrent.CompletableFuture.completedFuture(new com.turant.cellsite.TowerResolutionResult(towers, 3, 3, 0, List.of(3)));
            }
        };

        CapAlert alert = TestDataFixtures.createSampleCapAlert();
        String capId = "ews-pipeline-" + System.currentTimeMillis();
        var input = new com.turant.pipeline.AlertPipeline.RunPipelineInput(alert, capId, capId, src);

        var rec = alertPipeline.runAlertPipeline(input).get(30, TimeUnit.SECONDS);
        assertNotNull(rec);
        assertEquals(3, rec.towerCount());
        // Wait a bit for async EWS (though in current pipeline it's sync via EwsService.sendReport which is sync)
        Thread.sleep(500);

        // Verify local EWS received via store (proves pipeline → EwsService → LocalEwsClient → HTTP/in-memory → store)
        var lastReq = localStore.getLastRequest();
        assertNotNull(lastReq, "Local EWS should have received pipeline report");
        assertEquals(capId, lastReq.alertId());
        assertEquals(capId, lastReq.capIdentifier());
        assertNotNull(lastReq.payload(), "Payload should be AlertReport with real pipeline values");
        // Payload is AlertReport; check its fields via cast or JSON
        var payload = lastReq.payload();
        assertTrue(payload instanceof com.turant.types.report.AlertReport, "Payload should be AlertReport");
        var report = (com.turant.types.report.AlertReport) payload;
        assertEquals(capId, report.capIdentifier());
        assertEquals(capId, report.alertId());
        assertEquals(3, report.towerCount(), "Report towerCount must be real pipeline value (3)");
        assertTrue(report.targetedSubscriberCount() >= 3, "targetedSubscriberCount must be real (>=3)");
        assertNotNull(report.processingStartedAt());
        assertNotNull(report.processingEndedAt());

        // Verify response was stored
        var lastResp = localStore.getLastResponse();
        assertNotNull(lastResp);
        assertEquals("local", lastResp.mode());
        assertEquals("accepted", lastResp.status());
        assertTrue(lastResp.referenceId().startsWith("LOCAL-"));

        // Verify pipeline's EWS integration did not swallow failures and did not duplicate
        assertEquals(1, localStore.getReceivedCount(), "Exactly one EWS report per pipeline run");
    }

    @Test
    void ewsConfigurationSelectsLocalVsRemote() {
        props.setMode("local");
        assertEquals("local", new com.turant.ews.EwsClientFactory(new LocalEwsClient(props, "8080", null, null), new com.turant.ews.RemoteEwsClient(props), props).getClient().getMode());
        props.setMode("remote");
        props.setBaseUrl("http://localhost:18082");
        assertEquals("remote", new com.turant.ews.EwsClientFactory(new LocalEwsClient(props, "8080", null, null), new com.turant.ews.RemoteEwsClient(props), props).getClient().getMode());
        // reset
        props.setMode("local");
        props.setBaseUrl("");
        props.setLocalUrl("");
    }

    @Test
    void pipelineEwsViaHttpToControlledEndpoint() throws Exception {
        // Prove HTTP/network interaction actually happens: pipeline → LocalEwsClient → HTTP → MockServer
        props.setMode("local");
        props.setLocalUrl("http://localhost:18084/api/v1/ews/local/receive");
        ewsMockServer.when(request().withMethod("POST").withPath("/api/v1/ews/local/receive"))
                .respond(response().withStatusCode(200).withHeader("Content-Type", "application/json")
                        .withBody("{\"mode\":\"local\",\"status\":\"accepted\",\"referenceId\":\"LOCAL-HTTP-TEST\",\"timestamp\":\"2026-01-01T00:00:00Z\",\"alertId\":\"ews-http-001\",\"message\":\"ok\",\"code\":\"ACCEPTED\",\"httpStatus\":200}"));

        TowerSource src = new TowerSource() {
            @Override public String getName() { return "ews-http-test"; }
            @Override public java.util.concurrent.CompletableFuture<com.turant.cellsite.TowerResolutionResult> findTowersInZone(com.turant.types.tower.GeoZone z, FindTowersOptions o) {
                List<CellTower> towers = List.of(new CellTower("ews-site-1", "EWS-CELL-001", 28.611, 77.201, 500.0, null));
                return java.util.concurrent.CompletableFuture.completedFuture(new com.turant.cellsite.TowerResolutionResult(towers, 1, 1, 0, List.of(1)));
            }
        };
        CapAlert alert = TestDataFixtures.createSampleCapAlert();
        String capId = "ews-http-" + System.currentTimeMillis();
        var input = new com.turant.pipeline.AlertPipeline.RunPipelineInput(alert, capId, capId, src);
        var rec = alertPipeline.runAlertPipeline(input).get(30, TimeUnit.SECONDS);
        assertNotNull(rec);
        assertEquals(1, rec.towerCount());

        // Verify MockServer actually received the HTTP EWS report with real pipeline values
        var recorded = ewsMockServer.retrieveRecordedRequests(request().withPath("/api/v1/ews/local/receive"));
        assertTrue(recorded.length >= 1, "Local EWS HTTP endpoint should have received at least one POST");
        String body = recorded[0].getBodyAsString();
        assertTrue(body.contains(capId), "EWS payload must contain actual capId from pipeline: " + capId);
        assertTrue(body.contains("EWS-CELL-001") || body.contains("towerCount") || body.contains("targetedSubscriberCount"), "Payload should contain real pipeline data");
        System.out.println("[EWS PIPELINE HTTP] MockServer received: " + body.substring(0, Math.min(500, body.length())));

        // Reset localUrl to blank for other tests
        props.setLocalUrl("");
    }
}
