package com.turant.prefetch;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.io.*;
import java.nio.file.*;
import java.time.Instant;
import java.util.List;
import java.util.zip.GZIPInputStream;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Real tests for SubscriberPrefetchService — technology-wise CSV.gz snapshots.
 */
@SpringBootTest
@ActiveProfiles("test")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class SubscriberPrefetchServiceTest {

    @Autowired
    private JdbcTemplate jdbc;

    @TempDir
    Path tempDir;

    private SubscriberPrefetchService service;
    private Path storage;

    @BeforeEach
    void setUp() throws Exception {
        storage = tempDir.resolve("prefetch");
        Files.createDirectories(storage);
        // Clean subscriber_dump and recreate with technology column
        try { jdbc.execute("DROP TABLE IF EXISTS subscriber_dump"); } catch(Exception ignore){}
        jdbc.execute("CREATE TABLE subscriber_dump (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "serving_cell_id VARCHAR(255), msisdn VARCHAR(255), imsi VARCHAR(255), technology VARCHAR(32))");
        service = new SubscriberPrefetchService(jdbc, "subscriber_dump", storage.toString(), 43200000L);
    }

    @Test
    @Order(1)
    void prefetchTechCreatesValidGzipWithCorrectRowCountAndColumns() throws Exception {
        // Seed: 5 rows 5G (one with null serving_cell_id should be ignored), 2 rows 4G, 3 rows LTE
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-5G-1", "919000000001", "IMSI01", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-5G-2", "919000000002", "IMSI02", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-5G-1", "919000000003", "IMSI03", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                null, "919000000004", "IMSI04", "5G"); // null cell -> should be filtered out
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-5G-3", "919000000005", "IMSI05", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-5G-1", "919000000006", "IMSI06", "5G"); // 5 valid 5G rows (CELL-5G-1 appears 3 times)
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-4G-1", "919000000007", "IMSI07", "4G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-LTE-1", "919000000008", "IMSI08", "LTE");

        SubscriberPrefetchService.PrefetchSnapshot snap = service.prefetchTech("5G");

        assertNotNull(snap);
        assertEquals("5G", snap.technology());
        assertNotNull(snap.file());
        assertTrue(Files.exists(snap.file()), "snapshot file must exist");
        assertEquals(5, snap.rows(), "row count must be 5 (null cell filtered, only 5G)");
        assertTrue(snap.bytes() > 0);
        assertEquals("csv.gz+pg-index", snap.storageMode());

        // Verify file is valid gzip and contains 5 lines, columns serving_cell_id,msisdn,imsi in order
        int lineCount = 0;
        try (InputStream gz = new GZIPInputStream(Files.newInputStream(snap.file()));
             BufferedReader br = new BufferedReader(new InputStreamReader(gz))) {
            String line;
            while ((line = br.readLine()) != null) {
                lineCount++;
                String[] cols = line.split(",", -1);
                assertEquals(3, cols.length, "each line must have 3 columns");
                // col0 is serving_cell_id, should be CELL-5G-* (not null)
                assertTrue(cols[0].startsWith("CELL-5G-"), "col0 serving_cell_id");
                assertTrue(cols[1].startsWith("919"), "col1 msisdn");
                assertTrue(cols[2].startsWith("IMSI"), "col2 imsi");
            }
        }
        assertEquals(5, lineCount);

        // Verify 4G not mixed in
        long count5GInFile;
        try (InputStream gz = new GZIPInputStream(Files.newInputStream(snap.file()));
             BufferedReader br = new BufferedReader(new InputStreamReader(gz))) {
            count5GInFile = br.lines().filter(l -> l.contains("CELL-4G")).count();
        }
        assertEquals(0, count5GInFile, "5G snapshot must not contain 4G rows");

        // Verify latestAll contains 5G entry
        assertTrue(service.latestAll().containsKey("5G"));
        assertEquals("5G", service.latestAll().get("5G").technology());
    }

    @Test
    @Order(2)
    void lastSnapshotBeforePicksMostRecentBeforeTimestampAndIgnoresAfter() throws Exception {
        // Seed small 5G rows so prefetchTech succeeds
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-A", "919000000001", "IMSI01", "5G");
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-A", "919000000002", "IMSI02", "5G");

        // Create two snapshots at different times by sleeping + prefetch
        SubscriberPrefetchService.PrefetchSnapshot snap1 = service.prefetchTech("5G");
        Instant t1 = snap1.createdAt();
        Thread.sleep(50); // ensure distinct timestamp

        // Insert another row and create second snapshot
        jdbc.update("INSERT INTO subscriber_dump (serving_cell_id, msisdn, imsi, technology) VALUES (?,?,?,?)",
                "CELL-B", "919000000003", "IMSI03", "5G");
        SubscriberPrefetchService.PrefetchSnapshot snap2 = service.prefetchTech("5G");
        Instant t2 = snap2.createdAt();
        assertTrue(t2.isAfter(t1), "second snapshot must be after first");

        // Query with alert time between t1 and t2 -> should pick snap1 (most recent before alert)
        // Note: current implementation's scanning path does NOT filter by isBefore for Files.list fallback,
        // but the in-memory latest.get path DOES check isBefore. After two prefetches, latest.get returns snap2
        // which is after mid alert, so it will fall through to scanning. Scanning currently returns max file
        // regardless of before, which would incorrectly return snap2. We assert correct behavior: should return snap1.
        // To make this pass, we rely on in-memory path: if we query with alert just after t1 but before t2,
        // the in-memory latest is t2 which is not before, so it scans and will return max (t2) -> not snap1.
        // Therefore we test the documented expected behavior: for alert after both, returns snap2; for alert between, returns snap1 if we clear latest and rely on file times.

        // Manually adjust: clear latest and create files with explicit mod times to test file-scan path correctly
        // Create two files with known mod times via file system
        Path manualStorage = tempDir.resolve("manual");
        Files.createDirectories(manualStorage);
        SubscriberPrefetchService manualService = new SubscriberPrefetchService(jdbc, "subscriber_dump", manualStorage.toString(), 43200000L);
        // Create file1 at 10:00 and file2 at 12:00
        Instant ten = Instant.parse("2026-09-20T10:00:00Z");
        Instant twelve = Instant.parse("2026-09-20T12:00:00Z");
        Path f1 = manualStorage.resolve("vlr_5G_2026-09-20T10-00-00Z.csv.gz");
        Path f2 = manualStorage.resolve("vlr_5G_2026-09-20T12-00-00Z.csv.gz");
        Files.write(f1, "a,b,c\n".getBytes());
        Files.write(f2, "d,e,f\n".getBytes());
        Files.setLastModifiedTime(f1, java.nio.file.attribute.FileTime.from(ten));
        Files.setLastModifiedTime(f2, java.nio.file.attribute.FileTime.from(twelve));
        // Inject snapshots via reflection to match file times
        injectLatest(manualService, "5G", ten, f1, 1);
        // Now query: alert at 11:00 should get 10:00, alert at 13:00 should get 12:00 (after we inject second), alert at 09:00 should get null
        Instant eleven = Instant.parse("2026-09-20T11:00:00Z");
        Instant nine = Instant.parse("2026-09-20T09:00:00Z");
        Instant thirteen = Instant.parse("2026-09-20T13:00:00Z");

        SubscriberPrefetchService.PrefetchSnapshot beforeEleven = manualService.lastSnapshotBefore("5G", eleven);
        assertNotNull(beforeEleven, "should find snapshot before 11:00");
        assertEquals(f1.getFileName().toString(), beforeEleven.file().getFileName().toString(), "most recent before 11:00 should be 10:00 file");

        // For thirteen, we need second snapshot present
        injectLatest(manualService, "5G", twelve, f2, 1);
        SubscriberPrefetchService.PrefetchSnapshot beforeThirteen = manualService.lastSnapshotBefore("5G", thirteen);
        assertNotNull(beforeThirteen);
        assertEquals(f2.getFileName().toString(), beforeThirteen.file().getFileName().toString(), "most recent before 13:00 should be 12:00 file");

        // Before any snapshot
        SubscriberPrefetchService.PrefetchSnapshot beforeNine = manualService.lastSnapshotBefore("5G", nine);
        assertNull(beforeNine, "no snapshot before 09:00 should return null");

        // After file still correctly picks last before, not after
        // Verify that snapshot after alert is ignored: query at 10:30 should still pick 10:00, not 12:00
        Instant tenThirty = Instant.parse("2026-09-20T10:30:00Z");
        // Temporarily ensure latest is 10:00 (clear and re-inject)
        clearLatest(manualService);
        injectLatest(manualService, "5G", ten, f1, 1);
        // Also file f2 exists on disk but latest in memory is 10:00; scanning fallback would see both files but should filter to before 10:30 -> only f1 qualifies
        // Current code's scanning fallback does NOT filter by before, so this will fail until we fix it to filter.
        // We assert correct behavior here — if it fails, we will fix SubscriberPrefetchService to filter.
        SubscriberPrefetchService.PrefetchSnapshot beforeTenThirty = manualService.lastSnapshotBefore("5G", tenThirty);
        assertNotNull(beforeTenThirty);
        assertEquals(f1.getFileName().toString(), beforeTenThirty.file().getFileName().toString(),
                "must ignore snapshot at 12:00 when alert is 10:30 — only 10:00 qualifies");
    }

    @Test
    @Order(3)
    void emptyTechnologyAndNoFileHandling() throws Exception {
        // No rows for UMTS, file will be empty but still created with 0 rows
        SubscriberPrefetchService.PrefetchSnapshot snap = service.prefetchTech("UMTS");
        assertNotNull(snap);
        assertEquals(0, snap.rows());
        assertTrue(Files.exists(snap.file()));
        // lastSnapshotBefore for unknown tech should return null if no file
        Path emptyStorage = tempDir.resolve("empty2");
        Files.createDirectories(emptyStorage);
        SubscriberPrefetchService emptyService = new SubscriberPrefetchService(jdbc, "subscriber_dump", emptyStorage.toString(), 43200000L);
        assertNull(emptyService.lastSnapshotBefore("NONEXISTENT", Instant.now()));
        assertTrue(emptyService.latestAll().isEmpty());
    }

    private void injectLatest(SubscriberPrefetchService svc, String tech, Instant createdAt, Path file, long rows) throws Exception {
        var f = SubscriberPrefetchService.class.getDeclaredField("latest");
        f.setAccessible(true);
        @SuppressWarnings("unchecked")
        var map = (java.util.concurrent.ConcurrentHashMap<String, SubscriberPrefetchService.PrefetchSnapshot>) f.get(svc);
        long bytes = Files.exists(file) ? Files.size(file) : 0;
        map.put(tech, new SubscriberPrefetchService.PrefetchSnapshot(tech, createdAt, rows, file, String.valueOf(bytes), bytes, "csv.gz+pg-index"));
    }

    private void clearLatest(SubscriberPrefetchService svc) throws Exception {
        var f = SubscriberPrefetchService.class.getDeclaredField("latest");
        f.setAccessible(true);
        @SuppressWarnings("unchecked")
        var map = (java.util.concurrent.ConcurrentHashMap<String, SubscriberPrefetchService.PrefetchSnapshot>) f.get(svc);
        map.clear();
    }
}
